-- ============================================================
-- DAILY CODING TEST MODULE - SUPABASE
-- Run once in Supabase SQL Editor.
-- ============================================================
create extension if not exists pgcrypto;

create table if not exists public.coding_tests (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  instructions text,
  duration_minutes integer not null check (duration_minutes > 0),
  total_marks numeric not null default 0,
  starts_at timestamptz not null,
  ends_at timestamptz,
  status text not null default 'draft' check (status in ('draft','published','closed')),
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.coding_questions (
  id uuid primary key default gen_random_uuid(),
  test_id uuid not null references public.coding_tests(id) on delete cascade,
  question_number integer not null,
  title text not null,
  description text not null,
  difficulty text not null default 'Easy' check (difficulty in ('Easy','Medium','Hard')),
  marks numeric not null default 0,
  starter_code text,
  sample_input text,
  sample_output text,
  time_limit_ms integer not null default 3000,
  memory_limit_mb integer not null default 256,
  created_at timestamptz not null default now(),
  unique(test_id, question_number)
);

create table if not exists public.coding_test_cases (
  id bigint generated by default as identity primary key,
  question_id uuid not null references public.coding_questions(id) on delete cascade,
  input text,
  expected_output text not null,
  is_hidden boolean not null default true,
  marks numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.coding_attempts (
  id uuid primary key default gen_random_uuid(),
  test_id uuid not null references public.coding_tests(id) on delete cascade,
  register_number text not null,
  started_at timestamptz not null default now(),
  expires_at timestamptz not null,
  submitted_at timestamptz,
  status text not null default 'in_progress' check (status in ('in_progress','submitted','expired')),
  total_score numeric not null default 0,
  violation_count integer not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists coding_attempt_one_active
on public.coding_attempts(test_id, register_number);

create table if not exists public.coding_submissions (
  id uuid primary key default gen_random_uuid(),
  attempt_id uuid not null references public.coding_attempts(id) on delete cascade,
  question_id uuid not null references public.coding_questions(id) on delete cascade,
  source_code text not null default '',
  language text not null default 'java',
  passed_cases integer not null default 0,
  total_cases integer not null default 0,
  score numeric not null default 0,
  status text not null default 'draft',
  submitted_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(attempt_id, question_id)
);

create table if not exists public.coding_violations (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null references public.coding_attempts(id) on delete cascade,
  violation_type text not null,
  created_at timestamptz not null default now()
);

alter table public.coding_tests enable row level security;
alter table public.coding_questions enable row level security;
alter table public.coding_test_cases enable row level security;
alter table public.coding_attempts enable row level security;
alter table public.coding_submissions enable row level security;
alter table public.coding_violations enable row level security;

-- Public can read only published tests and their questions.
drop policy if exists "read published coding tests" on public.coding_tests;
create policy "read published coding tests" on public.coding_tests for select
using (status = 'published' or auth.role() = 'authenticated');

drop policy if exists "read coding questions" on public.coding_questions;
create policy "read coding questions" on public.coding_questions for select using (true);

-- IMPORTANT: hidden cases are intentionally NOT readable by anon.
drop policy if exists "read visible coding cases" on public.coding_test_cases;
create policy "read visible coding cases" on public.coding_test_cases for select
using (is_hidden = false or auth.role() = 'authenticated');

-- Existing admin login uses authenticated Supabase user.
drop policy if exists "admin manage coding tests" on public.coding_tests;
create policy "admin manage coding tests" on public.coding_tests for all to authenticated using (true) with check (true);
drop policy if exists "admin manage coding questions" on public.coding_questions;
create policy "admin manage coding questions" on public.coding_questions for all to authenticated using (true) with check (true);
drop policy if exists "admin manage coding cases" on public.coding_test_cases;
create policy "admin manage coding cases" on public.coding_test_cases for all to authenticated using (true) with check (true);

-- Prototype student-attempt policies. For production, replace these with
-- a student-authenticated flow / Edge Function so one student cannot query another.
drop policy if exists "anon create attempts" on public.coding_attempts;
create policy "anon create attempts" on public.coding_attempts for insert to anon with check (true);
drop policy if exists "anon read attempts" on public.coding_attempts;
create policy "anon read attempts" on public.coding_attempts for select to anon using (true);
drop policy if exists "anon update attempts" on public.coding_attempts;
create policy "anon update attempts" on public.coding_attempts for update to anon using (true) with check (true);

drop policy if exists "anon submissions" on public.coding_submissions;
create policy "anon submissions" on public.coding_submissions for all to anon using (true) with check (true);
drop policy if exists "anon violations" on public.coding_violations;
create policy "anon violations" on public.coding_violations for insert to anon with check (true);

-- Admin can inspect all attempts/results/violations.
drop policy if exists "admin attempts" on public.coding_attempts;
create policy "admin attempts" on public.coding_attempts for all to authenticated using (true) with check (true);
drop policy if exists "admin submissions" on public.coding_submissions;
create policy "admin submissions" on public.coding_submissions for all to authenticated using (true) with check (true);
drop policy if exists "admin violations" on public.coding_violations;
create policy "admin violations" on public.coding_violations for all to authenticated using (true) with check (true);

-- Recalculate total test marks from question marks.
create or replace function public.refresh_coding_test_marks()
returns trigger language plpgsql security definer as $$
begin
  update public.coding_tests
  set total_marks = coalesce((
    select sum(marks) from public.coding_questions
    where test_id = coalesce(new.test_id, old.test_id)
  ),0)
  where id = coalesce(new.test_id, old.test_id);
  return coalesce(new,old);
end $$;

drop trigger if exists coding_question_marks_refresh on public.coding_questions;
create trigger coding_question_marks_refresh
after insert or update or delete on public.coding_questions
for each row execute function public.refresh_coding_test_marks();
