-- Run this ONCE in Supabase -> SQL Editor -> New query -> Run.

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  register_number text not null unique,
  student_name text not null,
  leetcode_username text not null unique,
  created_at timestamptz not null default now()
);

alter table public.students enable row level security;

-- Public dashboard may read the student directory.
drop policy if exists "Public can read students" on public.students;
create policy "Public can read students"
on public.students for select
to anon
using (true);

-- Public Add Profile form may add a student.
-- Unique constraints prevent duplicate register numbers/usernames.
drop policy if exists "Public can add students" on public.students;
create policy "Public can add students"
on public.students for insert
to anon
with check (
  char_length(trim(student_name)) between 2 and 100
  and char_length(trim(register_number)) between 2 and 50
  and leetcode_username ~ '^[A-Za-z0-9_-]{1,50}$'
);

-- No public update/delete policies are created.
-- Only the GitHub Action (service_role key) can perform privileged reads.
